/*DATAMIGRATION 1AEC09FF-7BF8-4D8E-BB19-BBA85DFCD3F2*/ -- Change the script's code only if the it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'SimpleSPRTEmail', 'EmailFormat';
EXEC Rhetos.DataMigrationUse 'SimpleSPRTEmail', 'EmailFormat', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'SimpleSPRTEmail', 'EmailFormat', 'Subject', 'nvarchar(MAX)';
EXEC Rhetos.DataMigrationUse 'SimpleSPRTEmail', 'EmailFormat', 'Body', 'nvarchar(MAX)';
EXEC Rhetos.DataMigrationUse 'SimpleSPRTEmail', 'EmailFormat', 'IsBodyHtml', 'bit';
GO

IF NOT EXISTS (SELECT * FROM _SimpleSPRTEmail.EmailFormat)
BEGIN
	INSERT INTO _SimpleSPRTEmail.EmailFormat
		(ID, Subject, Body, IsBodyHtml)
	SELECT
		NEWID(),
		'Reset your password',
		'Please use the following token to reset your password:<br/><b>{Token}</b><br/>',
		1;
END

EXEC Rhetos.DataMigrationApplyMultiple 'SimpleSPRTEmail', 'EmailFormat', 'ID, Subject, Body, IsBodyHtml';
